---
title: "QM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(dplyr)
library(ez)

setwd("D:/Laurens/Documents/( School/CW 2/1e Semester/FMMI/R Project")

# Loading file
failData <- read.csv("failRate.csv")
levelData <- read.csv("highestLevels.csv")
timeData <- read.csv("totalTime.csv")

# Group data by gamemode
failGrouped <- group_by(failData, gamemode)

levelGrouped <- group_by(levelData, gamemode)

timeGrouped <- group_by(timeData, gamemode)

# Summary
summarise(failGrouped, MeanFail=mean(failrate), SDFail=sd(failrate))

summarise(levelGrouped, MeanLevel=mean(level), SDLevel=sd(level))

summarise(timeGrouped, MeanLevel=mean(totaltime), SDLevel=sd(totaltime))

# Boxplots

# Failrates
png(filename="D:/Laurens/Documents/( School/CW 2/1e Semester/FMMI/R Project/Graphs/Failrates.png")
failClassic <- filter(failData, gamemode == "Classic")
failBox1 <- select(failClassic, failrate)
boxplot(failBox1, at=1, xlim=c(0,3), boxwex=1.75, ylim=c(0,1), ylab="Failrate", main="Failrates per gamemode", xlab="Classic                                            ")

failEndurance <- filter(failData, gamemode == "Endurance")
failBox2 <- select(failEndurance, failrate)
boxplot(failBox2, at=2, add=TRUE, boxwex=1.75, ylim=c(0,1), xlab="                                              Endurance")
dev.off()

# Levels
png(filename="D:/Laurens/Documents/( School/CW 2/1e Semester/FMMI/R Project/Graphs/Levels.png")
levelClassic <- filter(levelData, gamemode == "Classic")
levelBox1 <- select(levelClassic, level)
boxplot(levelBox1, at=1, xlim=c(0,3), boxwex=1.75, ylim=c(0,max(levelBox1, levelBox2)),  ylab="Level", main="Hoogst behaalde level per gamemode", xlab="Classic                                            ")

levelEndurance <- filter(levelData, gamemode == "Endurance")
levelBox2 <- select(levelEndurance, level)
boxplot(levelBox2, at=2, add=TRUE, boxwex=1.75, ylim=c(0,max(levelBox1, levelBox2)), xlab="                                              Endurance")
dev.off()

# Total time played
png(filename="D:/Laurens/Documents/( School/CW 2/1e Semester/FMMI/R Project/Graphs/TimePlayed.png")
timeClassic <- filter(timeData, gamemode == "Classic")
timeBox1 <- select(timeClassic, totaltime)
boxplot(timeBox1, at=1, xlim=c(0,3), boxwex=1.75, ylim=c(0,max(timeBox1, timeBox2)),  ylab="Tijd in seconden", main="Totale speelduur per gamemode", xlab="Classic                                            ")

timeEndurance <- filter(timeData, gamemode == "Endurance")
timeBox2 <- select(timeEndurance, totaltime)
boxplot(timeBox2, at=2, add=TRUE, boxwex=1.75, ylim=c(0,max(timeBox1, timeBox2)), xlab="                                              Endurance")
dev.off()

# ANOVA analysis
failModel <- aov(failrate ~ gamemode, data=failData)
summary(failModel)

levelModel <- aov(level ~ gamemode, data=levelData)
summary(levelModel)

timeModel <- aov(totaltime ~ gamemode, data=timeData)
summary(timeModel)

```
